# Generated by Django 2.2.16 on 2023-02-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(help_text='Введите описание группы', verbose_name='Описание группы'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(help_text='Введенный вами текст будет автоматически переведен в транслит и обрезан до 100 символов.', null=True, unique=True, verbose_name='Адресс для страницы группы'),
        ),
    ]
